spring:
  application:
    name: cloud-gateway
  security:
    user:
      name: getir
      password: 1234

server:
  port: 8000
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka

jwt:
  header: Authorization
  secret: secretkey